# Generated by Django 5.2.6 on 2025-10-05 09:05

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
